services:
  php:
    container_name: php
    build:
      context: .docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/symfony
      - ./.docker/php/90-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - symfony-network
    depends_on:
      pokemon-db:
        condition: service_healthy

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/symfony
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony-network
    depends_on:
      - php

  pokemon-db:
    container_name: pokemon-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE:-symfony}
      MYSQL_USER: ${DB_USERNAME:-symfony}
      MYSQL_PASSWORD: ${DB_PASSWORD:-symfony}
    ports:
      - '3355:3306'
    volumes:
      - pokemon-data:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h localhost -u ${DB_USERNAME:-symfony} -p${DB_PASSWORD:-symfony}"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - symfony-network

volumes:
  pokemon-data:

networks:
  symfony-network:
